### ISSUE TITLE
how do i run the mmpi test

### ISSUE THREAD

**Issue by eusinbay** [nucular/mmpi-2#1]
hi, 

i have downloaded the files and uploaded it into github desktop. how do i get it to run?

apologies for the noob question. 

eusinbay

**Comment by eusinbay** [comment]
hi, i managed to resolved it. thanks!

**Comment by i3130002** [comment]
> hi, i managed to resolved it. thanks!

Wish you have gave us a clue

**Comment by i3130002** [comment]
For whom that reads this. You have to provide `/data/questions.json` file for it to work. I have yet to discover report generation.
